### ISSUE TITLE
error when setting security when a window open

### ISSUE THREAD

**Issue by craigham** [QuailAutomation/openhab2-addons#13]
When a window is open if I try and change to day or night security, get the following 

`2017-06-11 16:45:23.620 [DEBUG] [io.rest.core.item.ItemResource:288  ] - Received HTTP POST request at 'items/omnilink_area_1_mode' with value '2'.
2017-06-11 16:45:23.621 [INFO ] [arthome.event.ItemCommandEvent:43   ] - Item 'omnilink_area_1_mode' received command 2
2017-06-11 16:45:23.622 [DEBUG] [.c.thing.internal.ThingManager:355  ] - Delegating command '2' for item 'omnilink_area_1_mode' to handler for channel 'omnilink:area:1:mode'
2017-06-11 16:45:23.623 [DEBUG] [b.omnilink.handler.AreaHandler:29   ] - handleCommand: omnilink:area:1:mode, command: 2
2017-06-11 16:45:23.623 [DEBUG] [b.omnilink.handler.AreaHandler:57   ] - Setting mode 50 on area 1
2017-06-11 16:45:23.624 [INFO ] [smarthome.event.ItemStateEvent:43   ] - omnilink_area_1_mode updated to 2
2017-06-11 16:45:23.625 [DEBUG] [.c.thing.internal.ThingManager:405  ] - Delegating update '2' for item 'omnilink_area_1_mode' to handler for channel 'omnilink:area:1:mode'
2017-06-11 16:45:23.626 [INFO ] [s.event.ItemStateChangedEvent :43   ] - omnilink_area_1_mode changed from 0 to 2
2017-06-11 16:45:23.657 [DEBUG] [.o.b.o.h.OmnilinkBridgeHandler:98   ] - Error in sendOmnilinkCommandcom.digitaldan.jomnilinkII.OmniInvalidResponseException: null
	at com.digitaldan.jomnilinkII.Connection.controllerCommand(Connection.java:708)
	at org.openhab.binding.omnilink.handler.OmnilinkBridgeHandler$2.run(OmnilinkBridgeHandler.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

`

**Comment by digitaldan** [comment]
That's because the system is responding with something other then a ACK (probably an NACK), which means it could not process the message b/c the action could not be completed (window was open).   I'll catch the specific OmniInvalidResponseException and reset the state.

Question, I noticed you have wrapped command calls in a guava Future library, out of curiosity, what's the benefit of doing this?

**Comment by craigham** [comment]
The intent is to make all calls to the external system (omnilink here) non-blocking, so it submits the future, and then with callbacks handles the response whenever they come back.  

I've been working on a couple other bindings and my research I found others doing it.  Seemed like a good idea.  

Its not the most intuitive thing to see at first, but I've gotten pretty used to it now.  Just let me know if you think we should revisit this decision, I have no problem with that.

**Comment by craigham** [comment]
The BaseThingHandler class makes a schedule available to the bridge handers, so I see it as receiving a command from OH, then tossing the work onto a scheduler to make the call and hit the callback, and then can let OH get back at things without getting blocked.

**Comment by digitaldan** [comment]
In this case we need to know if it's successful or not,  so do we pass in a failure callback?  This will be true for any object (unit/zone/area/etc...) that we send a command to.  In this case if the call fails we need to not set the mode to armed, when it's still off.

 For requests like handling commands, I'm not sure a future makes sense.  If I'm executing a REST command, or even a rule, if I send a command, I would expect it to return once the command has been properly processed.  If I look at a binding like the Hue (which is in the ESH project and I consider a reference binding), it makes direct blocking calls and does not use a future or executor.  

>The BaseThingHandler class makes a schedule available to the bridge handers, 

The primary reason for that was for polling code, so that the system supplied a executor service that was managed vs creating your own thread pools. But it's also used for other things, but I would not say its there for offloading commands like this per se.  

Now I think futures make sense for other parts, like in the initialize call of the binding, you don't want to block the system starting up, so this is often done in the executor service.

So my opinion is to not use a executor or similar for commands, but I'm ok for other things like the initial connection or reconnects.

**Comment by craigham** [comment]
It's an interesting discussion.

I do believe there is value in using non-blocking calls to external systems.  e.g. SocketTimeouts can take forever, and there are other potential delays.  Unfortunately I don't have a nice concise sales pitch on it, so please Indulge me by letting me ramble a little about what I perceive to be some of the factors.  

I haven't checked the call stack of the command dispatcher (the thing calling all the handleCommand methods), but for example with the handleCommand method, it is a void method, and I wouldn't expect much error handling behind it other than ignore.  So I take from this that if we return from the handleCommand call before we have a result, no real problem.  That default behavior around autoupdate is a factor of course.

So I assume it really is just notifying the appropriate handlers of commands and then moving on, the next task for the dispatcher is not dependent on the prior....   

With the non-blocking calls, you can always register callbacks to get the results of your calls, it just doesn't have to happen on that command dispatcher thread.  

Most commands in something like Hue or even this binding are expected to happen relatively quickly.  But in keeping with your reasoning, should setting the mode for the security system block until the delay period is over, and the status on the Omni has truly changed?   Or closing a garage door, or roller shutters?  I've seen there where the command is different than the status.  So you might issue a close door command, with the knowledge the door is going to take some time to close.  So you might have the actuator to initiate the close, and then a sensor, or without a sensor you would have to assume it closed.  

I do also believe that some of these things don't matter too much on our home systems which might be processing 10 commands a minute, but what happens in other domains with 10000 commands a minute.  Blocking could presumably bring the system to a crawl.

just my 2 cents.

**Comment by digitaldan** [comment]
Since you started the binding, I will defer to you :-)

But... I'm for keeping this as simple as possible, as thin as possible. If you feel strongly , then I'm ok, I will just need some way of handling command failures in the individual handlers. If you can put that in we can just go forward. 

>but in keeping with your reasoning, should setting the mode for the security system block until the delay period is over, and the status on the Omni has truly changed?

I think this is extreme and not what I was saying, it should block until the system acknowledges (ACK) or rejects the command (NACK) . if this does not return quickly then there is a larger problem and the binding should be marked as failed.  Any other blocking is self imposed and is not what I implied.

Again, the Hue binding is a good template, this is co-written by Kai and I think shows how both the executor service and commands are designed to be used. Its commands could be argued as even worse than ours as they are HTTP requests that don't have a constantly connected socket. 

If you decide to keep the future pattern, then again I just need some way for the handlers to know that their commands were not accepted by the system.  I think we will be fine either way.

**Comment by digitaldan** [comment]
>I haven't checked the call stack of the command dispatcher 

So I was thinking about this and realized I was making a lot of assumptions, but to be honest, I was not sure about this either, appently calls to a things handleCommand are already scheduled in a seperate thread, see
https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/internal/ThingManager.java#L374

I decided to test this with a sleep statement in my handler, sure enough sending commands from say the rest interface returns immediately.  I was incorrect in my assumptions that they were synchronous!  Shows how much I know.

**Comment by craigham** [comment]
Dan,

Thanks for figuring that out.  

There seems to be no need to do non-blocking from the handleCommand now.  That will lighten up the code for sure.

To confirm, is that your takeaway too?

**Comment by craigham** [comment]
And one more thing, earlier I got into the discussion with you, and didn't answer on of your questions.

In the code where it called

`getOmnilinkBridgeHander().sendOmnilinkCommand(mode, 1, number);`

I could have wrapped it with the addCallaback method as shown below, and that exact code is just above for area refresh.  You'll notice the onFailure method which would have been called when the OmniException was thrown.  
`Futures.addCallback(getOmnilinkBridgeHander().getAreaStatus(Integer.parseInt(channelParts[2])),
                    new FutureCallback<AreaStatus>() {

                        @Override
                        public void onFailure(Throwable arg0) {
                            logger.error("Failure getting status", arg0);
                        }

                        @Override
                        public void onSuccess(AreaStatus status) {
                            logger.debug("handle area status: {}", status);
                            handleAreaEvent(status);
                        }
                    });`


So, point is that we could have handled the omni exception and fixed state to how we wanted with non-blocking.  

This isn't trying to make the case for the non-blocking your other discovery makes that mute, but I just wanted to point out how you could do it in a non-blocking in other circumstances.

**Comment by digitaldan** [comment]
That's my thought as well, that handlers can call directly.  I still think that the bridge should at least abstract the call a bit so that it can also catch exceptions, so if a command has a socket issue, the bridge can disconnect, set to offline and reschedule a connection before returning an exception (or something) to the calling code.  wdyt?

**Comment by digitaldan** [comment]
>So, point is that we could have handled the omni exception and fixed state to how we wanted with non-blocking.

Ahh, ok sounds good, I like the callback pattern they use.  Again, I know we have kicked this dead horse over and over :-)  but I'm ok either way!

**Comment by craigham** [comment]
ya, totally agree.

 it's not enforced via code at this time because I believe I do make the
connection to the jomniink Connection from the bridge handler, but I have
coded all the other handlers to call a method on the bridge and it calls
the methods on the Connection.  so, that getConnection should not be used,
and made private soonish is my point.

e.g. there is a getUnitStatus method on the bridge handler, instead of the
unit handler calling getObjectStatus (or whatever that method is on
Connection)

**Comment by craigham** [comment]
No, full agreement by me to pull out the non-blocking now.  It was my
oversight to not check the dispatch thread/read the docs to see how
handleCommand was called.

**Comment by digitaldan** [comment]
>e.g. there is a getUnitStatus method on the bridge handler

I wonder if we should have a "sendCommand" function that wraps command calls?  in the 1.x binding we have https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.omnilink/src/main/java/org/openhab/binding/omnilink/internal/OmniLinkCommandMapper.java , i think that logic now lives in each handler , so tha handler knows what wierd parameters each command needs and the bridge remains a more simple conduit.

**Comment by craigham** [comment]
Dan, can we continue this over on this issue? 
https://github.com/QuailAutomation/openhab2-addons/issues/15

I'll respond there to your last sendCommand question

**Comment by digitaldan** [comment]
I think this issue can be closed with what has been merged in

**Comment by craigham** [comment]
awesome work.
