### ISSUE TITLE
UPB Unit Types

### ISSUE THREAD

**Issue by swamiller** [QuailAutomation/openhab2-addons#92]
I have several UPB units that are controlling electric motors or non-dimmable lights.  Currently the binding makes all UPB units channel type "level".  I tried overriding in my .items file to a "switch" type channel but the binding still recognizes as a "level" type unit. 

Default:
```
Switch PlPumpUnit_Switch   "Pl PumpUnit"  (Misc) {channel="omnilink:upb:home:65:level"} 
```

Tested:
```
Switch PlPumpUnit_Switch  "Pl PumpUnit"  (Misc) {channel="omnilink:upb:home:65:switch"} 
```

**Comment by craigham** [comment]
@digitaldan, @boc-tothefuture Do you think we should add a switch channel to Upb Units which could be used for these non-dimming switches?  If I remember correctly we could mark as Advanced, and then it doesn't automatically get linked to an item when simple linking is turned on.

Any other idea?  I do work on an Isy binding, and that returns model numbers of each of the switches so I can tell the difference from a simple switch and one with a dimmer.  Haven't seen that with the omnilink.

**Comment by swamiller** [comment]
Is there a programatic reason the omnilink channels have to have a "type" definition in the channel?  Meaning, the beginning of the item says what type you want then the channel has it declared again.  

Any way to let the initial declaration determine the channel type?

**Comment by digitaldan** [comment]
the level channel is a Dimmer item type, Dimmers accept both ON/OFF as well as Percent commands so they can operate as both a Switch and a Dimmer.   You should be able to map both a Switch and Dimmer item to this channel.  The Unit/UPB handler needs to accept both types (Percent/ ON_OFF) in the handleCommand method, I just looked at the code and it looks like it it only accepting PercentType, so that's probably why its not working.

**Comment by digitaldan** [comment]
Btw I was incorrect , upb handler is accepting on/off types ( sorry I missed the map lookup) .  So maybe I am not understanding the issue here?

**Comment by digitaldan** [comment]
@craigham regarding adding another channel for switch, What would be the benefit over the dimmer type channel?  It's too bad we don't get back more info about the type of upb device

**Comment by boc-tothefuture** [comment]
I have been using UPB switches in my setup without issue:

Thing definition:
`Thing upb master_bedroom_brian_lamp "Master Bedroom Brian's Lamp" @ "Master Bedroom" [number=83]`

Item:
`Switch Lights_Master_Brian_Lamp "Master Bedroom Brian's Lamp [%s]" { channel="omnilink:upb:home:master_bedroom_brian_lamp:level" }`

Sitemap:
`Switch item=Lights_Master_Brian_Lamp label="Brian's Lamp [%s]" icon="light"`

**Comment by swamiller** [comment]
This unit isn't a typical unit (like a light switch).  I'm controlling my pool pump using a Simply Automated UMI-32 I/O module.  The module has the ability to send a momentary contact to my pool pump controller which simulates pushing the pump button. The I/O module also has a voltage sense that sends back a UPB "link" to my omnipro confirming there is power to the relay and the pump is actually on/off.

Through programming in PC Access, I have created a virtual "Unit" that I can switch on and off and will also reflect the state of the pump as on/off.   The pumps are actually turned on using a programmed "button" in PC access and I use flags to hold the on/off state of the Unit.  Turning the virtual unit switch on checks the state of the sensing flag to confirm the pump isn't already on and then triggers a programmed button that sends the momentary contact to the I/O unit to turn the pump on.  Switching the "unit" switch off does the opposite.

This shows up as just another "unit" in openHAB and looks and works like a regular on/off switch.  It works in v1.9 binding.  I have only tried using the Paper UI using v2 binding but it doesn't work. 
 
Here is the item for v1.9 :
```
Switch	PlPumpUnit_Switch	"Pl PumpUnit"	(Misc)	{omnilink="unit:65"}
```
Item file the 2.x version:
```
Switch` PlPumpUnit_Switch   "Pl PumpUnit"  (Misc) {channel="omnilink:upb:home:65:level"} 
```
Admittedly, this is a bit more than just a light switch but openHAB shouldn't see this unit as anything different than just a non-dimmable light switch.

For the record, I control my garage doors and my gate using the same type I/O units.  I know some that use them for monitoring motion sensor triggers.  They are great devices for expanding the usage of UPB.

**Comment by boc-tothefuture** [comment]
@swamiller - your item definitions looks ok to me.   If you turn on debug mode what do you see happens when you turn the switch on in openhab2?

**Comment by swamiller** [comment]
Ok, more to the story...nothing bad in the log and I was able to make the pump come on. But the fact the only option in the PaperUI is a slider (versus a switch) the control was sporadic.  Moving the slider on to the far right setting (100) made the pump come on then turn off.  Sliding back down to zero would turn the pump off some of the time. Sliding back to 100 (or anything in between) will sometimes turn the pump on.

I can use my phone app (Haiku, not openHAB) to turn the pump on and off and OH logs correctly as state 0 and state 100.  The nice feature you guys have added is I can see the flags switching and the button push I programmed in PC Access!  

It would be nice to be able to select a simple non-dimmable on/off switch.

**Comment by boc-tothefuture** [comment]
@swamiller - Ok, so its really a paperUI issue.
Hmm. I don't use paperUI. I use a sitemap and set it to type 'switch' rather than type 'dimmer'.  Maybe @digitaldan or @craigham have some ideas on how to handle this in paperUI.

**Comment by BCS-JonW** [comment]
I would like to see support for a "switch" type in addition to the "level" type on UPB units.  I have several UPB units configured for non-dimming applications as well as actual appliance modules which are strictly on/off capabilities.  When defining these with a level channel, they show a percentage indicator in the BasicUI even when the button is configured for switch.

**Comment by mdedonato** [comment]
I see a similar issues when using the alexa integration and a dimmer.  When the lights are set directly to 100% via alexa (not using a slider) the lights do not respond.  Setting the light to 99% using alexa, results in proper operation.

**Comment by 2MuchTech** [comment]
FWIW, this is how it works with Alexa talking to an openHAB 1.x installation as well.  My system uses Leviton's Vizia RF+ switches (defined simply as a "unit" in the 1.x binding), and you have to tell Alexa 99% instead of 100% if you want full brightness.

**Comment by 2MuchTech** [comment]
@boc-tothefuture : in your example of an Item and Thing several posts up, you have the unit number defined in the Thing.  Other places that discuss OH2 and omnilink show the unit number defined in the Item.  Is there documentation somewhere that describes exactly what the correct syntax is for the omnilink binding for Items and Things?

I’ve been experimenting with Units in my .items file in OH2, and so far I’m seeing no difference in how OH2 processes things regardless of what I have in the channel definition at the end of the Item line, so I’m pretty sure I’ve got the parameters wrong.  As best I can tell, having the OmniPro Unit # in the Items file doesn’t change which physical light OH2 operates on, so I’m thinking the examples people have been posting of .items files with unit numbers aren’t correct, and that the unit number needs to be in the .things file.

**Comment by boc-tothefuture** [comment]
@mdedonato - What voice command are you issuing over Alexa?  I essentially just use the 'on' and 'off' command which works correctly.

**Comment by boc-tothefuture** [comment]
@2MuchTech - 
  When you use auto discovery in the paperUI the items files will have a omnilnk number the name of the 'thing' and that will be part of the UID (unique identifier) that is referenced as a channel.  Changing the number field in the item channel definition changes the thing the item links to not what the omnilink binding controls.  This is a Openhab 2.0 thing - not unique to the omnilink binding.

In terms of flow: 
Item -> Thing -> Omnilink
More info:  
[Things](https://docs.openhab.org/configuration/things.html)
[Items] (https://docs.openhab.org/configuration/items.html)

Now to answer your other question.  I don't use autodiscovery (which you can see in the example above).  I prefer to keep all my openhab configuration in text files under source control so I can test out changes, revert them, etc.  So I don't discover things using the paperUI.  When you define things manually the only thing that tells the binding which unit to talk to is the number property on the Thing definition.  

> I’ve been experimenting with Units in my .items file in OH2, and so far I’m seeing no difference in how OH2 processes things regardless of what I have in the channel definition at the end of the Item line, so I’m pretty sure I’ve got the parameters wrong. As best I can tell, having the OmniPro Unit # in the Items file doesn’t change which physical light OH2 operates on, so I’m thinking the examples people have been posting of .items files with unit numbers aren’t correct, and that the unit number needs to be in the .things file.

That is correct - in terms of physical 'thing' - its all about the .things file.

**Comment by 2MuchTech** [comment]
I'm just not getting this.  It would be immensely helpful if OH2 could write auto-discovered Things and Items into a .things and .items file so one can see the exact syntax required.

I am having no luck getting this to work when I manually create the .things and .items files.  When I tried defining the Thing as just a "upb", it complained that it didn't know what a upb was, so I tried prefacing it with the word "OmniLink".  I now have a Thing showing up in PaperUI, but it shows the Status as UNINITIALIZED - HANDLER_INITIALIZING_ERROR.  If I edit the Thing, the Bridge Selection is blank.  If I choose "Omnilink controller - omnilink:controller:45a1bd38" for the Bridge, when I save the changes it says "Thing Updated", then "Error 409 - Conflict".

Here's a part of my setup files... please tell me what the heck I'm doing wrong.

.things file:
Thing omnilink:upb:Light_L1_Kitchen_Ceiling "Kitchen_Ceiling" @ "Kitchen" [number=18]


.items file:
Group Inside							(All)
Group gL1				<groundfloor>	(Inside)		// Group for Level 1 (main level)
Group L1_Kitchen		"Kitchen"			<kitchen>		(gL1)

/* Lights in Upstairs area */
Dimmer Light_L1_Kitchen_Ceiling	        "Kitchen Ceiling"		(L1_Kitchen)		{channel="omnilink:upb:home:Light_L1_Kitchen_Ceiling:level"}

I have more groups defined than what's shown above, and it is correctly parsing all of my groups and displaying them in PaperUI.  I just can't get to the point where I have a Thing that actually changes the physical lighting level from the PaperUI.

**Comment by boc-tothefuture** [comment]
your things file should be
`Thing upb Light_L1_Kitchen_Ceiling  "Kitchen_Ceiling" @ "Kitchen" [number=18]`

items file:
`Dimmer Light_L1_Kitchen_Ceiling "Kitchen Ceiling [%d]"	(L1_Kitchen) {channel="omnilink:upb:home:Light_L1_Kitchen_Ceiling:level"}`

**Comment by 2MuchTech** [comment]
Perhaps I've got something else misconfigured?  I tried your suggestion above, and still no go.  Here's my info:

default.items:
Group All
Group Inside							(All)
Group Outside							(All)
Group gL0				<cellar>		(Inside)		// Group for Level 0 (basement)
Group gL1				<groundfloor>	(Inside)		// Group for Level 1 (main level)
Group gGarage			<garage>		(Inside)		// Group for Garage fluorescent lights
Group gOutsideFloods					(Outside)		// All outside flood lights
Group gOutside							(Outside)		// All outside lights

Group L1_Greatroom		"Greatroom"			<sofa>			(gL1)
Group L1_Kitchen		"Kitchen"			<kitchen>		(gL1)
Group L1_Kitchen_Accent	"Kitchen Accent"	<kitchen>		(Inside)	// don't want these to be part of the Level 1 group because turning off gL1 lights at night should leave these on
Group L1_Breakfast		"Breakfast"			<corridor>		(gL1)
Group L1_DeskArea		"Desk Area"			<dryer>			(gL1)
Group L1_Foyer			"Foyer"				<corridor>		(gL1)

Group L0_Gameroom		"Game Area" 		<corridor>		(gL0)
Group L0_Theater		"Theater Area" 		<television>	(gL0)

Group OF_Floods			"Front Floods"		<hue>			(gOutsideFloods, gOutside)	// Group for Outside Front Floods
Group OB_Floods			"Back Floods"		<hue>			(gOutsideFloods, gOutside)	// Group for Outside Back Floods
Group Landscape			"Landscape"			<hue>			(gOutside)					// Low Voltage Landscape Lights
Group Entryway			"Entryway"			<hue>			(gOutside)					// Entryway Lights

Dimmer Light_L1_Kitchen_Ceiling	        "Kitchen Ceiling [%d]"		(L1_Kitchen)		{channel="omnilink:upb:home:Light_L1_Kitchen_Ceiling:level"}


default.things:
Thing upb Light_L1_Kitchen_Ceiling "Kitchen_Ceiling" @ "Kitchen" [number=18]


Here's a section of my Log file after startup.  Note that it's complaining about a missing bridge for the Thing from the .things file.

22:32:57.091 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'default.items'
22:32:57.726 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'default.sitemap'
22:32:57.732 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'Light_L1_Kitchen_Ceiling-omnilink:upb:home:Light_L1_Kitchen_Ceiling:level' has been added.
22:32:57.774 [INFO ] [el.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'default.things', using it anyway:
Provide a thing UID in this format:
 <bindingId>:<thingTypeId>:<thingId>
22:32:57.775 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'default.things'
22:32:57.778 [WARN ] [.thing.internal.GenericThingProvider] - Thing upb does not have a bridge so it needs to be defined in full notation like <bindingId>:upb:Light_L1_Kitchen_Ceiling
22:32:57.791 [INFO ] [home.event.ItemChannelLinkAddedEvent] - Link 'Light_L1_Kitchen_Ceiling-omnilink:upb:Light_L1_Kitchen_Ceiling:level' has been added.
22:32:57.820 [INFO ] [smarthome.event.ThingAddedEvent     ] - Thing 'omnilink:area:45a1bd38:1' has been added.
22:32:57.821 [INFO ] [smarthome.event.ThingAddedEvent     ] - Thing 'omnilink:controller:45a1bd38' has been added.
22:32:57.984 [WARN ] [g.eclipse.smarthome.core.net.NetUtil] - Found multiple local interfaces - ignoring 192.168.1.138
22:32:57.985 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at http://192.168.1.91:8080
22:32:57.986 [WARN ] [g.eclipse.smarthome.core.net.NetUtil] - Found multiple local interfaces - ignoring 192.168.1.138
22:32:57.986 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at https://192.168.1.91:8443
22:32:58.036 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
22:32:58.069 [INFO ] [arthome.ui.paper.internal.PaperUIApp] - Started Paper UI at /paperui
22:32:58.097 [INFO ] [panel.internal.HABPanelDashboardTile] - Started HABPanel at /habpanel
22:32:58.296 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'omnilink:area:45a1bd38:1' changed from UNINITIALIZED to UNINITIALIZED (BRIDGE_UNINITIALIZED)
22:32:58.341 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'omnilink:controller:45a1bd38' changed from UNINITIALIZED to INITIALIZING
22:32:59.329 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'omnilink:controller:45a1bd38' changed from INITIALIZING to ONLINE
22:32:59.343 [WARN ] [.thing.internal.GenericThingProvider] - Thing upb does not have a bridge so it needs to be defined in full notation like <bindingId>:upb:Light_L1_Kitchen_Ceiling
22:32:59.354 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'omnilink:area:45a1bd38:1' changed from UNINITIALIZED (BRIDGE_UNINITIALIZED) to INITIALIZING
22:32:59.460 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'omnilink:area:45a1bd38:1' changed from INITIALIZING to ONLINE


If I manually create a Thing in PaperUI, I can set its bridge to the OmniLink, and I can link the Thing to the Item that imported from the .items file.  After doing this I can control the Kitchen Ceiling light.  So why isn't my .things file creating the Thing?  It seems that everything is working EXCEPT being able to import Things, and I have a LOT of Units (i.e. Lights) in my system, so I would really like to be able to create a .things file that defines all of them.

**Comment by boc-tothefuture** [comment]
@2MuchTech - 
 Can you paste your complete things file?  Also, what was the reason you wren't using auto-discovery in the paper UI?  I can't recall.

**Comment by 2MuchTech** [comment]
I have only the one line in my .things file.  Once I figure out what OH2 is looking for I’ll populate it with the rest of my things.

I’m not able to use autodiscovery because OmniLink doesn’t recognize Units as Things, and all of my light switches/dimmers are Leviton Vizia RF+ devices, which are generic “unit”s in the OmniPro II.

**Comment by craigham** [comment]
@2MuchTech have you tried to manually create a upb unti using paper ui?  If you know the unit number you should be able to create the thing/item via the GUI.

**Comment by 2MuchTech** [comment]
If I use PaperUI to manually create a Thing and an Item (and link them), I can control them from PaperUI without any apparent issues.  But I have a lot of lights in my system, and I would really prefer to maintain .things and .items files... just in case something in the OH2 database goes awry (I'm already seeing evidence of potential problems... I've deleted previously added Items and Things and I'm still seeing references to them pop up in the Log file... not exactly confidence inspiring).  It would suck to have to start over creating new devices one at a time.  If AutoDiscovery was working I would be less concerned about having config files, but given the current state of AutoDiscovery not being able to find Units, the manually maintained config files have strong appeal.

The frustrating thing is that this used to work so easily in OH1.  All I needed was a file with my Items in it, and everything worked well!  OH2 has injected a whole additional level of complexity and difficulty with the introduction of Things.

**Comment by craigham** [comment]
@2MuchTech ya, I realize it is no fun adding a bunch of lights manually.  I just wanted to get a sense of how it worked when it was set up.  

I unfortunately haven't gotten to putting my things and items in files yet.  I agree, they are much more stable when specified like that.  I have been spread a little thin trying to contribute on 3 different bindings.

@boc-tothefuture Do you think we should adjust auto-discovery to create all units as what we call UPb units for now, and let others raise issues if their light types don't work with our binding implementation for units?  

@2MuchTech Even if we did add auto-discovery for your type of lights you probably want to keep spending the time to figure out how to specify your configuration via the text files.

**Comment by boc-tothefuture** [comment]
@2MuchTech - 
 Ahh - Ok, so if you just have "things" in a things file not inside of a bridge file, then openhab won't know what binding to use to control that thing.

File should look like this:
```
Bridge omnilink:controller:home [ ipAddress="<ip>", port=4369, key1="<key1>", key2="<key2>"] {
  //Alarms
   Thing area house [number=1]
  
  //Thermostats
   Thing thermostat downstairs "Downstairs Thermostat" @ "Foyer" [ number=1 ]
   Thing thermostat upstairs "Upstairs Thermostat" @ "Upstairs Hallway" [ number=2 ]
   
   //Garage Doors
   Thing zone garage1 "Garage Door 1" @ "Garage" [number=23]
   Thing zone garage2 "Garage Door 2" @ "Garage" [number=24]
   
   //Doors
   Thing zone mudroom_door "Mudroom Door" @ "Basement" [number=17]
   Thing zone front_door "Front Door" @ "Foyer" [number=18]
   Thing zone deck_door "Deck Door" @ "Foyer" [number=19]
   Thing zone basement_door "Basement Door" @ "Basement" [number=20]
   Thing zone workshop_door "Workshop Door" @ "Basement" [number=21]
   Thing zone garage_side_door "Garage Side Door" @ "Foyer" [number=22]

   //Automation Zones
   Thing zone cat_beam  "Cat beam" @ "Mudroom" [number=29]
   
   //Flags
   Thing flag work_at_home "Work at Home" [number=393]
   Thing flag vacation "Vacation" [number=412]

//Lights
   Thing room media_room "Media Room Scenes" @ "Media Room" [ number=105 ]
   Thing upb media_room_front_recessed "Media Room Front Recessed " @ "Media Room" [ number=106 ]  
   Thing upb media_room_rear_recessed "Media Room Rear Recessed " @ "Media Room" [ number=107 ] 
   Thing upb media_room_fan "Media Room Fan Light " @ "Media Room" [ number=108 ] 

...
```

**Comment by 2MuchTech** [comment]
Okay, now things are starting to make sense!  I hadn't seen anything in the docs about the Bridge definition in the .things file :-(  I'm possibly not completely out of the woods yet, but I've added a few entries and it doesn't seem to be complaining anymore.  Let me get my entire list of devices in the .items and .things files and I'll report back.  Progress!  Thank you!

BTW, is there an easy way to completely delete the database in OH2 so I can start over?  I'd like to flush out all of the test Things and Items that I created while trying to get it to work, and I'm finding that some of them won't delete from PaperUI.

**Comment by craigham** [comment]
I believe you can stop openHAB, then delete the files in the
userdata/jsondb folder.

Then restart.

Maybe backup before you try that though

**Comment by mdedonato** [comment]
@boc-tothefuture, Since it is a dimmer I sometimes use the set level command.  i.e. "Alexa, Set the Kitchen lights to 50%"  or "Alexa, set the Kitchen lights to 100%"  The 100% setting does not go to full brightness.  If I issue the following commands in order "Alexa, set the Kitchen lights to 100%" then "Alexa, set the Kitchen lights to 99%" then the lights go brighter.

**Comment by craigham** [comment]
I have both Insteon and upb lights, so I might be confusing the two technologies, but I can set an ‘on level’ attribute for lights, so when they are turned on with the paddle, they only go to 80%.  This sounds like the issue you are running into.  You are sending an on command to the light, but it might not consider on as full brightness.
